-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.m_application
(
    id_pk integer NOT NULL,
    application_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    application_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    repository character varying(300) COLLATE pg_catalog."default" NOT NULL,
    repo_owner character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT m_application_pk PRIMARY KEY (id_pk),
    CONSTRAINT m_application_uk UNIQUE (application_code)
);

CREATE TABLE IF NOT EXISTS public.m_company
(
    id_pk integer NOT NULL,
    company_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    company_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    CONSTRAINT m_company_pk PRIMARY KEY (id_pk),
    CONSTRAINT m_company_uk UNIQUE (company_code)
);

CREATE TABLE IF NOT EXISTS public.m_company_product_group_mpg
(
    id_pk integer NOT NULL,
    company_id integer NOT NULL,
    product_group_id integer NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    CONSTRAINT m_comany_product_group_mpg_pkey PRIMARY KEY (id_pk)
);

CREATE TABLE IF NOT EXISTS public.m_pg_product_mpg
(
    id_pk integer NOT NULL,
    product_group_id integer NOT NULL,
    product_id integer NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    CONSTRAINT m_pg_product_mpg_pk PRIMARY KEY (id_pk)
);

CREATE TABLE IF NOT EXISTS public.m_product
(
    id_pk integer NOT NULL,
    product_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    CONSTRAINT m_product_pk PRIMARY KEY (id_pk),
    CONSTRAINT m_product_uk UNIQUE (product_code)
);

CREATE TABLE IF NOT EXISTS public.m_product_application_mpg
(
    id_pk integer NOT NULL,
    product_id integer NOT NULL,
    application_id integer NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    CONSTRAINT m_product_application_mpg_pkey PRIMARY KEY (id_pk)
);

CREATE TABLE IF NOT EXISTS public.m_product_group
(
    id_pk integer NOT NULL,
    product_group_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_group_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_dt timestamp without time zone NOT NULL,
    CONSTRAINT m_product_group_pk PRIMARY KEY (id_pk),
    CONSTRAINT m_product_group_uk UNIQUE (product_group_code)
);

ALTER TABLE IF EXISTS public.m_company_product_group_mpg
    ADD CONSTRAINT m_comany_product_group_mpg_fk1 FOREIGN KEY (company_id)
    REFERENCES public.m_company (id_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.m_company_product_group_mpg
    ADD CONSTRAINT m_comany_product_group_mpg_fk2 FOREIGN KEY (product_group_id)
    REFERENCES public.m_product_group (id_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.m_pg_product_mpg
    ADD CONSTRAINT m_pg_product_mpg_fk1 FOREIGN KEY (product_group_id)
    REFERENCES public.m_product_group (id_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.m_pg_product_mpg
    ADD CONSTRAINT m_pg_product_mpg_fk2 FOREIGN KEY (product_id)
    REFERENCES public.m_product (id_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.m_product_application_mpg
    ADD CONSTRAINT m_product_application_mpg_fk1 FOREIGN KEY (product_id)
    REFERENCES public.m_product (id_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.m_product_application_mpg
    ADD CONSTRAINT m_product_application_mpg_fk2 FOREIGN KEY (application_id)
    REFERENCES public.m_application (id_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;